#define VS_VERSION_INFO                 1
#define ID_ETNAME                       101
#define ID_ETADDRESS                    102
#define ID_ETAGES                       103
#define ID_ETA                          104
#define ID_ETSALPS                      105
#define ID_RBMARRIED                    106
#define ID_RBUNMARRIED                  107
#define ID_PBCONTIE                     108
#define IDK                             109
#define IDCANCEL                         110
#define DATAENTRY                       111
#define IDC_STATIC                      -1
#define ID_ETM1							112
